FROM python:3.10

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

CMD ["python3.10", "recommendation_system_app.py", "--config_file", "app/config/backend-providers-recommender-prod.yaml"]
