VERSION_NAME: "v3"
MODE: "PORTAL-RECOMMENDER"

FASTAPI:
  WORKERS: 1
  DEBUG: True
  RELOAD: True
  HOST: '0.0.0.0'
  PORT: 4559

# In dev no scheduled updates will occur
SCHEDULING:
  EVERY_N_HOURS: 1

CREDENTIALS: "credentials.yml"

SPACY_MODEL: "en_core_web_sm"

SIMILAR_SERVICES:
  METADATA: ["categories", "scientific_domains"]
  TEXT_ATTRIBUTES: ["description"]

  METADATA_WEIGHT: 0.25
  VIEWED_WEIGHT: 0.5

  DIVERSITY_WEIGHT: 0.0
  SENTENCE_FILTERING_METHOD: "NONE"  # NONE, KEYWORD, NER

  METHOD: "SBERT" # tf-idf or SBERT
  SBERT:
    MODEL_NAME: 'all-MiniLM-L6-v2'
    DEVICE: "cpu"

PROJECT_ASSISTANT:
  SIMILARITY_THRESHOLD: 0.5

PROJECT_COMPLETION:
  MIN_SUPPORT: 0.05
  MIN_CONFIDENCE: 0.5

AUTO_COMPLETION:
  RESOURCE_TYPES:
    service:
      TEXT_ATTRIBUTES: ["description"]
      ENUMERATED_FIELDS:
        categories:
          VOCABULARY_TYPE: "SUBCATEGORY"
          SIMILARITY_THRESHOLD: 0.5
          CONSIDERED_SERVICES_THRESHOLD: 5
          FREQUENCY_THRESHOLD: 0.1
        scientific_domains:
          VOCABULARY_TYPE: "SCIENTIFIC_SUBDOMAIN"
          SIMILARITY_THRESHOLD: 0.5
          CONSIDERED_SERVICES_THRESHOLD: 5
          FREQUENCY_THRESHOLD: 0.1
  TAGS:
    KEYWORD_EXTRACTION_METHOD: "textrank"
    SCORE_WEIGHT: 0.0
    MAX_WORDS: 3
    PHRASES_SIM_THRESHOLD: 0.7
    PHRASES_EQUAL_THRESHOLD: 0.9
